on:
  pull_request:
    branches:
    - master

name: Hello Workflow


jobs:

  build:
    runs-on: ubuntu-latest
    actions:

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - run: |
        env
